version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WsLambdaAtEdgeAlienCardsSAM"
s3_prefix = "WsLambdaAtEdgeAlienCardsSAM"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"

